# Generated by Django 6.0.6 on 2026-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ticket_created', 'Ticket creado'), ('assigned', 'Asignado'), ('new_message', 'Nuevo mensaje'), ('status_changed', 'Cambio de estado'), ('sla_at_risk', 'SLA en riesgo'), ('sla_breached', 'SLA vencido')], max_length=32),
        ),
    ]
