"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent


def _env(name, default=""):
    return os.environ.get(name, default)


def _env_bool(name, default):
    return _env(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


def _env_csv(name, default):
    return [x.strip() for x in _env(name, default).split(",") if x.strip()]


# Placeholder de dev: el system check config.E001 impide arrancar prod con este valor.
DEV_SECRET_KEY_PLACEHOLDER = "CHANGE_ME__PUT_YOUR_OWN_SECRET_KEY_HERE"
SECRET_KEY = _env("DJANGO_SECRET_KEY", DEV_SECRET_KEY_PLACEHOLDER)

DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")

# Application definition
INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",
    "tenancy",
    "accounts",
    "billing",
    "users",
    "tickets_t",
    "notifications",
    "sla",
    "csat",
    "metrics",
    "channels",
    "landing_cms",
    "django_cleanup.apps.CleanupConfig",

    # Local apps (descomenta cuando existan)
    # "tickets",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS debe ir arriba (antes de CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tenancy.middleware.OrganizationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # si usas templates propios pon aquí rutas
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Database (MySQL)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": _env("DB_NAME", "allsafe"),
        "USER": _env("DB_USER", "root"),
        "PASSWORD": _env("DB_PASSWORD", "root"),
        "HOST": _env("DB_HOST", "127.0.0.1"),
        "PORT": _env("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# Redis (G): con REDIS_URL seteado, channels + cache van a Redis (multi-proceso).
# Sin REDIS_URL (dev), quedan los backends in-process de siempre.
REDIS_URL = _env("REDIS_URL")

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "es-mx"  # puedes dejar "en-us" si prefieres
TIME_ZONE = _env("TIME_ZONE", "America/Mexico_City")
USE_I18N = True
USE_TZ = True

# H2: base pública del frontend (links de verificación/invitación por email)
FRONTEND_BASE_URL = _env("FRONTEND_BASE_URL", "http://localhost:5173")

# H3: billing / Stripe (usado en T3-T4)
STRIPE_SECRET_KEY = _env("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = _env("STRIPE_WEBHOOK_SECRET")
STRIPE_PUBLISHABLE_KEY = _env("STRIPE_PUBLISHABLE_KEY")

# Static files
STATIC_URL = "static/"
STATIC_ROOT = _env("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles"))

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------
# CORS para Vue (SPA)
# -----------------------
# Vite usa 5173 por default y sube al siguiente puerto libre si está ocupado.
_DEV_ORIGINS = ",".join(
    f"http://{h}:{p}" for h in ("localhost", "127.0.0.1") for p in (5173, 5174, 5175)
)
CORS_ALLOWED_ORIGINS = _env_csv("CORS_ALLOWED_ORIGINS", _DEV_ORIGINS)

# Si vas a enviar Authorization: Bearer <token>
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# -----------------------
# DRF + JWT
# -----------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "config.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "contact": "5/hour",
        "register": "5/hour",
        "resend": "5/hour",
    },
}

# Cache (presence de notificaciones). LocMem en dev; Redis si REDIS_URL está seteado (G).
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "allsafe-default",
        }
    }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

CORS_ALLOW_CREDENTIALS = True  # clave para enviar cookies al frontend

CSRF_TRUSTED_ORIGINS = _env_csv("CSRF_TRUSTED_ORIGINS", _DEV_ORIGINS)

# En dev (HTTP) lo más estable es Lax.
# Si pones SameSite=None, muchos browsers exigen Secure=True (HTTPS) y en local te puede fallar.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Recomendado para que el navegador mande cookies en cross-origin fetch:
CSRF_COOKIE_HTTPONLY = False  # el token csrf (si lo usas) suele necesitar leerse en JS

# Email: Mailtrap (u otro SMTP) por env en dev; console si no hay EMAIL_HOST.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "AllSafe <no-reply@allsafe.local>")

# Envío de emails en thread daemon (no bloquea WS/request). En tests se pone False.
NOTIFICATIONS_EMAIL_ASYNC = True

# -----------------------
# Seguridad HTTP (prod)
# -----------------------
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_REDIRECT_EXEMPT = [r"^api/health/$"]  # healthcheck de compose entra por http directo
SECURE_HSTS_SECONDS = int(_env("SECURE_HSTS_SECONDS", "0" if DEBUG else "3600"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_REFERRER_POLICY = "same-origin"

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Cookies JWT (config/auth_views.py)
AUTH_COOKIE_SECURE = _env_bool("COOKIE_SECURE", not DEBUG)