# Generated by Django 6.0.6 on 2026-07-03 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_t', '0002_ticketmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Creado'), ('assigned', 'Asignado'), ('unassigned', 'Desasignado'), ('status_changed', 'Cambio de estado'), ('reopened', 'Reabierto'), ('priority_changed', 'Cambio de prioridad')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets_t.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='tickets_t_t_ticket__0e8249_idx')],
            },
        ),
    ]
