# Generated by Django 6.0.6 on 2026-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_t', '0004_seed_created_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
