# Generated by Django 6.0.6 on 2026-07-04 15:50

import tickets_t.models
import tickets_t.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_t', '0005_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tickets_t.models.attachment_upload_to, validators=[tickets_t.validators.validate_attachment]),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
