# Generated by Django 6.0.3 on 2026-07-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_organizationbranding'),
        ('tickets_t', '0008_ticket_organization_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('instagram', 'Instagram'), ('widget', 'Widget web')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_accounts', to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_id'), name='uniq_channel_external_id')],
            },
        ),
        migrations.CreateModel(
            name='ChannelThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('instagram', 'Instagram'), ('widget', 'Widget web')], max_length=20)),
                ('contact_external_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_threads', to='tenancy.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_threads', to='tickets_t.ticket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'channel', 'contact_external_id'), name='uniq_thread_per_contact')],
            },
        ),
    ]
