# Generated by Django 6.0.3 on 2026-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelaccount',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('widget', 'Widget web')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channelthread',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('widget', 'Widget web')], max_length=20),
        ),
    ]
