# Generated by Django 6.0.3 on 2026-07-01 02:50

import landing_cms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_es', models.TextField(blank=True)),
                ('mission_en', models.TextField(blank=True)),
                ('vision_es', models.TextField(blank=True)),
                ('vision_en', models.TextField(blank=True)),
                ('values_es', models.TextField(blank=True)),
                ('values_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_es', models.TextField(blank=True)),
                ('subtitle_en', models.TextField(blank=True)),
                ('primary_cta_label_es', models.CharField(default='Iniciar sesión', max_length=50)),
                ('primary_cta_label_en', models.CharField(default='Sign in', max_length=50)),
                ('primary_cta_url', models.CharField(default='/login', max_length=200)),
                ('secondary_cta_label_es', models.CharField(default='Contactar', max_length=50)),
                ('secondary_cta_label_en', models.CharField(default='Contact us', max_length=50)),
                ('secondary_cta_url', models.CharField(default='#contacto', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', validators=[landing_cms.validators.validate_image_file])),
                ('footer_text_es', models.TextField(blank=True)),
                ('footer_text_en', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
