# Generated by Django 6.0.3 on 2026-07-01 03:08

import landing_cms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=50)),
                ('title_es', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours_es', models.CharField(blank=True, max_length=200)),
                ('hours_en', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locations/', validators=[landing_cms.validators.validate_image_file])),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('SUCURSAL', 'Sucursal'), ('OFICINA', 'Oficina'), ('CENTRO', 'Centro de servicio')], default='OFICINA', max_length=20)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', validators=[landing_cms.validators.validate_image_file])),
                ('name', models.CharField(max_length=100)),
                ('role_es', models.CharField(blank=True, max_length=100)),
                ('role_en', models.CharField(blank=True, max_length=100)),
                ('bio_es', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
