# Generated by Django 6.0.3 on 2026-07-29 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_organizationbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=30)),
                ('public_rate_limit_per_hour', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'configuración de IA',
                'verbose_name_plural': 'configuraciones de IA',
            },
        ),
    ]
