# Generated by Django 6.0.3 on 2026-07-29 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('tenancy', '0003_organizationbranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaisettings',
            name='monthly_budget_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='tenancy.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ai_aiusage_organiz_1087c4_idx')],
            },
        ),
    ]
