# Generated by Django 6.0.6 on 2026-07-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets_t', '0006_ticketmessage_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SlaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_timezone', models.CharField(default='America/Mexico_City', max_length=64)),
                ('work_days', models.CharField(default='1,2,3,4,5', max_length=20)),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='18:00')),
                ('at_risk_threshold_pct', models.PositiveIntegerField(default=25)),
                ('scheduler_interval_minutes', models.PositiveIntegerField(default=10)),
                ('scheduler_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20, unique=True)),
                ('first_response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_met_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('fr_level', models.CharField(default='ok', max_length=12)),
                ('res_level', models.CharField(default='ok', max_length=12)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='tickets_t.ticket')),
            ],
        ),
    ]
