# Generated by Django 6.0.6 on 2026-07-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_seed_policies'),
        ('tenancy', '0002_seed_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_config', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('organization', 'date'), name='uniq_holiday_org_date'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'priority'), name='uniq_policy_org_priority'),
        ),
    ]
