# Generated by Django 6.0.6 on 2026-07-20 03:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seed_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('accent_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser hex de 6 dígitos, ej. #0038FF.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('default_dark', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenancy.organization')),
            ],
        ),
    ]
